- name: download promtail to localhost
  become: false
  run_once: true
  delegate_to: localhost
  get_url:
    url: "{{ _archive_url }}"
    dest: "{{ role_path }}/files/{{ _archive }}"
    checksum: "sha256:{{ _archive_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2

- name: create promtail system group
  group:
    name: "{{ promtail_group }}"
    state: present
  when: promtail_group != "root"

- name: create promtail system user
  user:
    name: "{{ promtail_user }}"
    shell: "/sbin/nologin"
    group: "{{ promtail_group }}"
    create_home: false
    state: present
  when: promtail_user != "root"

- name: create promtail directories
  file:
    path: "{{ dir.value.path }}"
    state: directory
    owner: "{{ dir.owner | default(promtail_user) }}"
    group: "{{ dir.group | default(promtail_group) }}"
    mode: "{{ dir.value.mode | default(755) }}"
  loop: "{{ promtail_dirs | dict2items }}"
  loop_control:
    loop_var: dir
    label: "{{ dir.value.path }}"

- name: create archive directory
  become: false
  delegate_to: localhost
  file:
    state: directory
    path: "{{ _archive_dir }}"

- name: unpack promtail
  become: false
  delegate_to: localhost
  unarchive:
    src: "{{ role_path }}/files/{{ _archive }}"
    dest: "{{ _archive_dir }}"
    creates: "{{ _archive_dir }}/promtail-linux-{{ _arch }}"

- name: propagate promtail binary
  copy:
    src: "{{ _archive_dir }}/promtail-linux-{{ _arch }}"
    dest: "/usr/bin/promtail"
    owner: root
    group: root
    mode: 0555
  notify: restart promtail

- name: delete archive directory
  become: false
  delegate_to: localhost
  file:
    dest: "{{ _archive_dir }}"
    state: absent
  when: not lookup("env", "MOLECULE_SCENARIO_NAME") | default("")

- name: create promtail configuration
  tags: configs
  copy:
    content: "{{ promtail_config | to_nice_yaml }}"
    dest: "{{ promtail_dir }}/promtail.yml"
    owner: "{{ promtail_user }}"
    group: "{{ promtail_group }}"
    mode: 0640
  notify: restart promtail

- name: create promtail service file
  tags: config
  copy:
    content: "{{ promtail_service }}"
    dest: "/etc/init.d/promtail"
    owner: root
    group: root
    mode: 0755
  notify: restart promtail
  when: ansible_service_mgr == "openrc"

- name: enable promtail
  service:
    name: promtail
    enabled: true
  when: ansible_service_mgr == "openrc"

- name: create promtail unit file
  tags: config
  copy:
    content: "{{ promtail_unitfile }}"
    dest: "/etc/systemd/system/promtail.service"
    owner: root
    group: root
    mode: 0755
  notify: restart promtail
  when: ansible_service_mgr == "systemd"

- name: enable promtail
  systemd:
    name: promtail
    enabled: true
    daemon_reload: true
  when: ansible_service_mgr == "systemd"
