- name: restart promtail
  service:
    name: promtail
    state: restarted
  when: not skip_handlers

- name: reload promtail
  service:
    name: promtail
    state: reloaded
  when: not skip_handlers
